### ISSUE TITLE
"tool" table not present in pyproject.toml

### ISSUE THREAD

**Issue by leandrolanzieri** [carderne/una#10]
Following the quickstart (https://una.rdrn.me/quickstart/), I get the following error when trying to create the workspace: `NonExistentKey: 'Key "tool" does not exist.'`. The error seems to be due to these lines, which try to access dictionary keys without checking first whether they exist: https://github.com/carderne/una/blob/77e5a67cdb4a3f9b928e0f9cfc79a3adb880c3b8/una/una/files.py#L155-L157

Upon creation of a new project with uv, and after adding una, my pyproject.toml looks like this:
```toml
[project]
name = "una-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "una>=0.5.2",
]
```

My uv version is `uv 0.6.3 (a0b9f22a2 2025-02-24)`.
